### ISSUE TITLE
ValueError: no valid index for a 0-dimensional object (velocity_hourly)

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodntools#124]
Occurs for sites WACA20, GBRMYR
```
Traceback (most recent call last):
  ...
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/aodndata/moorings/products_handler.py", line 393, in preprocess
    self._make_velocity_hourly_timeseries()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/aodndata/moorings/products_handler.py", line 317, in _make_velocity_hourly_timeseries
    **self.product_common_kwargs)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/aodntools/timeseries_products/velocity_hourly_timeseries.py", line 212, in velocity_hourly_aggregated
    slice_end = append_resampled_values(nc_cell[varlist], ds, slice_start, binning_fun)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/aodntools/timeseries_products/velocity_hourly_timeseries.py", line 57, in append_resampled_values
    df_cell = nc_cell.squeeze().to_dataframe()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/xarray/core/dataset.py", line 3088, in to_dataframe
    return self._to_dataframe(self.dims)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/xarray/core/dataset.py", line 3078, in _to_dataframe
    index = self.coords.to_index(ordered_dims)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/xarray/core/coordinates.py", line 80, in to_index
    raise ValueError('no valid index for a 0-dimensional object')
ValueError: no valid index for a 0-dimensional object
```

**Comment by mhidas** [comment]
This issue occurrs when the chunk of data being averaged includes only a single time step.
